---
abstract: 'Clean Unit Testing'
author:
  - 'Pieter van de Bruggen <pvande@cpan.org>'
build_requires:
  B: 0
  File::Find: 0
  File::Temp: 0
  Mock::Collection: 0
  Test::More: 0
  Text::Outdent: 0.01
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mini
recommends: {}
requires:
  B::Hooks::EndOfScope: 0
  B::Hooks::OP::Check: 0.18
  Class::MOP: 1.00
  Data::Inspect: 0.03
  Devel::Declare: 0.006
  Devel::Declare::Context::Simple: 0
  Exception::Class: 1.29
  Getopt::Long: 0
  IO::Scalar: 2.110
  List::MoreUtils: 0
  List::Util: 1.21
  Scalar::Util: 1.21
  Sub::Install: 0
  Sub::Name: 0
  Text::Outdent: 0.01
  Try::Tiny: 0.04
  aliased: 0
  perl: 5.008
resources:
  homepage: http://github.com/pvande/Test-Mini
  repository: git://github.com/pvande/Test-Mini.git
version: 0.06
